-- sql
CREATE TABLE cuenta_digital (
                                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                usuario_id BIGINT NOT NULL UNIQUE,
                                saldo DECIMAL(10,2) DEFAULT 0.00,
                                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                                updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                                FOREIGN KEY (usuario_id) REFERENCES public."user"(id) ON DELETE CASCADE
);

CREATE TABLE recarga_cuenta (
                                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                cuenta_digital_id BIGINT NOT NULL,
                                monto DECIMAL(10,2) NOT NULL,
                                fecha_recarga TIMESTAMP NOT NULL,
                                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                                FOREIGN KEY (cuenta_digital_id) REFERENCES cuenta_digital(id) ON DELETE CASCADE
);

CREATE INDEX idx_cuenta_usuario ON cuenta_digital(usuario_id);
CREATE INDEX idx_recarga_cuenta ON recarga_cuenta(cuenta_digital_id);
CREATE INDEX idx_recarga_fecha ON recarga_cuenta(fecha_recarga);
