services:
  postgres:
    container_name: postgres_congreso
    image: 'postgres:latest'
    restart: unless-stopped
    environment:
      - 'POSTGRES_DB=Congreso'
      - 'POSTGRES_PASSWORD=Congreso-db'
      - 'POSTGRES_USER=Congreso-root'
    ports:
      - '5433:5432'
    volumes:
      - pg_congreso_data:/data/postgres
volumes:
  pg_congreso_data: